### ISSUE TITLE
Замечания по CopyFile

### ISSUE THREAD

**Issue by alexey-malov** [AlexDorohoff/OOP#1]
- [x] Выделить из main функцию, копирующую файлы, заданные именами

```c++
bool CopyFiles(const std::string& inputFileName, const std::string& outputFileNAme)
```

**Comment by alexey-malov** [comment]
- [ ] Рекомендуется явно вызывать return 0 внутри main

**Comment by alexey-malov** [comment]
- [ ] результат flush следует проверять

**Comment by alexey-malov** [comment]
- [ ] удалить лишние пустые строки, взять нормальный .clangformat или добавить перевод строки в конце файла

**Comment by AlexDorohoff** [comment]
каким образом проверить выполнение flush?

**Comment by alexey-malov** [comment]
- [ ] CopyFile/CopyStream путают возвращаемые значения true/false. Возвращать следует true/false, а не 1/0.

**Comment by alexey-malov** [comment]
```c++
	if (!CopyStream(inputFile, outputFile))
	{
		return false;
	}
	return true;
```

- [ ] Можно написать проще: `return CopyStream(inputFile, outputFile);`
